<?php
/** 
* cache.category.php
*
* @package    YIGECMS
* @author     
* @copyright  Copyright (c) 2008-2010  (http://www.YIGECMS.cn)
* @license    http://www.YIGECMS.cn/license.txt
   
*/

if (!defined('YIGECMS')) exit();

return array (
  0 => 
  array (
    'id' => '14',
    'module' => 'Download',
    'parent_id' => '0',
    'title' => '下载模块',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '下载模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411171',
    'update_time' => '1342680191',
  ),
  1 => 
  array (
    'id' => '15',
    'module' => '',
    'parent_id' => '14',
    'title' => '系统软件',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '系统软件',
    'display_order' => '1',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411182',
    'update_time' => '1262411190',
  ),
  2 => 
  array (
    'id' => '1',
    'module' => 'Article',
    'parent_id' => '0',
    'title' => '文章模块',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '1',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  3 => 
  array (
    'id' => '17',
    'module' => '',
    'parent_id' => '14',
    'title' => '恢复类软件',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '恢复类软件',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411216',
    'update_time' => '0',
  ),
  4 => 
  array (
    'id' => '33',
    'module' => '',
    'parent_id' => '32',
    'title' => '首页横幅',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '首页横幅',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112629',
    'update_time' => '1267288982',
  ),
  5 => 
  array (
    'id' => '32',
    'module' => 'Ad',
    'parent_id' => '0',
    'title' => '广告模块',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '广告模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112377',
    'update_time' => '1267112406',
  ),
  6 => 
  array (
    'id' => '34',
    'module' => '',
    'parent_id' => '32',
    'title' => '公共',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '公共',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112648',
    'update_time' => '0',
  ),
  7 => 
  array (
    'id' => '35',
    'module' => 'Link',
    'parent_id' => '0',
    'title' => '链接类型',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '链接类型',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267287014',
    'update_time' => '0',
  ),
  8 => 
  array (
    'id' => '36',
    'module' => '',
    'parent_id' => '35',
    'title' => '默认类型',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '普通链接',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267287066',
    'update_time' => '1267288647',
  ),
  9 => 
  array (
    'id' => '99',
    'module' => '',
    'parent_id' => '72',
    'title' => '公司活动',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1324554041',
    'update_time' => '0',
  ),
  10 => 
  array (
    'id' => '131',
    'module' => '',
    'parent_id' => '129',
    'title' => '法律法规',
    'biaozhi' => 'falvfagui‘',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1380617153',
    'update_time' => '0',
  ),
  11 => 
  array (
    'id' => '84',
    'module' => '',
    'parent_id' => '72',
    'title' => '员工天地',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1316584975',
    'update_time' => '1324554013',
  ),
  12 => 
  array (
    'id' => '94',
    'module' => '',
    'parent_id' => '93',
    'title' => '企业文化',
    'biaozhi' => '',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1316832672',
    'update_time' => '1324552285',
  ),
  13 => 
  array (
    'id' => '123',
    'module' => '',
    'parent_id' => '1',
    'title' => '行业新闻',
    'biaozhi' => 'hangyexinwen',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1351919657',
    'update_time' => '1380617001',
  ),
  14 => 
  array (
    'id' => '124',
    'module' => '',
    'parent_id' => '1',
    'title' => '公司新闻',
    'biaozhi' => 'gongsixinwen',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1352128047',
    'update_time' => '1380616977',
  ),
  15 => 
  array (
    'id' => '117',
    'module' => '',
    'parent_id' => '32',
    'title' => '分页广告',
    'biaozhi' => 'fenye',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1351916455',
    'update_time' => '0',
  ),
  16 => 
  array (
    'id' => '132',
    'module' => 'Page',
    'parent_id' => '0',
    'title' => '单页管理',
    'biaozhi' => 'guanyuwomen',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1380617214',
    'update_time' => '1380617227',
  ),
  17 => 
  array (
    'id' => '133',
    'module' => '',
    'parent_id' => '132',
    'title' => '关于我们',
    'biaozhi' => 'guanyuwomen',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1380617249',
    'update_time' => '0',
  ),
  18 => 
  array (
    'id' => '134',
    'module' => '',
    'parent_id' => '132',
    'title' => '服务项目',
    'biaozhi' => 'fuwuxiangmu',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1380617266',
    'update_time' => '0',
  ),
  19 => 
  array (
    'id' => '130',
    'module' => '',
    'parent_id' => '129',
    'title' => '国家法规',
    'biaozhi' => 'guojiafagui',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1380617127',
    'update_time' => '0',
  ),
  20 => 
  array (
    'id' => '129',
    'module' => 'Fagui',
    'parent_id' => '0',
    'title' => '政策法规',
    'biaozhi' => 'fagui',
    'html_url' => '',
    'menu' => '0',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1380617111',
    'update_time' => '0',
  ),
);